# Generated by Django 3.1 on 2020-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
